# Generated by Django 6.0.5 on 2026-09-28 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_selected_variations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('province', models.CharField(choices=[('ON', 'Ontario'), ('BC', 'British Columbia'), ('AB', 'Alberta'), ('QC', 'Quebec'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island')], max_length=2)),
                ('billing_address', models.JSONField()),
                ('shipping_address', models.JSONField()),
                ('cardholder_name', models.CharField(max_length=200)),
                ('card_last4', models.CharField(max_length=4)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=250)),
                ('selected_variations', models.CharField(blank=True, default='', max_length=500)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.order')),
            ],
        ),
    ]
