# Generated by Django 5.2.11 on 2026-03-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('strings', 'strings'), ('material', 'material'), ('key_count', 'key count'), ('package_set', 'package set')], max_length=100),
        ),
    ]
